# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'RecipeRack' do
pod 'Alamofire'
pod 'SwiftyJSON'
end

target 'RecipeRackUITests' do

end
